"""
Groq LLM signal for AI detection.

Uses llama-3.3-70b-versatile to perform semantic analysis of whether text
was likely written by a human or generated by an AI. This signal captures
patterns that heuristics miss: reasoning structure, factual hedging style,
and characteristic AI discourse patterns.

Returns a probability [0.0, 1.0] that the text is AI-generated.
"""

import os
import json
from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY not set in environment")
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an expert content attribution analyst. Your job is to determine whether a given piece of text was written by a human or generated by an AI writing tool.

Analyze the text carefully for:
- Formulaic structures and hedging language typical of AI (e.g., "It is worth noting that", "Furthermore", "In conclusion")
- Natural irregularities, personal voice, and idiosyncratic style typical of human writing
- Emotional authenticity and personal anecdotes vs. generic examples
- Syntactic diversity and risk-taking vs. safe, averaged phrasing
- Whether the text feels "averaged" across many styles or distinctively personal

You MUST respond with valid JSON only. No explanation outside the JSON.
Format:
{
  "ai_probability": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence explaining your top signal>",
  "top_indicators": ["<indicator 1>", "<indicator 2>"]
}

Where 0.0 = definitely human, 1.0 = definitely AI-generated."""


USER_PROMPT_TEMPLATE = """Analyze this text for AI vs. human authorship:

---
{text}
---

Respond with JSON only."""


def analyze(text: str) -> dict:
    """
    Query Groq LLM to classify the text and return a detection signal.

    Returns:
        {
            "signal_name": "groq_llm",
            "ai_probability": float,
            "reasoning": str,
            "top_indicators": list[str],
            "confidence": float,
            "error": str | None,
        }
    """
    try:
        client = _get_client()
    except RuntimeError as e:
        return {
            "signal_name": "groq_llm",
            "ai_probability": 0.5,
            "reasoning": "",
            "top_indicators": [],
            "confidence": 0.0,
            "error": str(e),
        }

    truncated = text[:4000]  # Stay within context limits

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=truncated)},
            ],
            temperature=0.1,
            max_tokens=300,
            response_format={"type": "json_object"},
        )

        raw = response.choices[0].message.content
        parsed = json.loads(raw)

        ai_prob = float(parsed.get("ai_probability", 0.5))
        ai_prob = max(0.0, min(1.0, ai_prob))

        # LLM signal has high confidence when it gives extreme scores
        confidence = 0.5 + abs(ai_prob - 0.5) * 0.9

        return {
            "signal_name": "groq_llm",
            "ai_probability": round(ai_prob, 4),
            "reasoning": parsed.get("reasoning", ""),
            "top_indicators": parsed.get("top_indicators", []),
            "confidence": round(confidence, 4),
            "error": None,
        }

    except Exception as e:
        return {
            "signal_name": "groq_llm",
            "ai_probability": 0.5,
            "reasoning": "",
            "top_indicators": [],
            "confidence": 0.0,
            "error": str(e),
        }
