"""
Multi-signal ensemble detection pipeline.

Combines three signals using confidence-weighted averaging with an asymmetric
false-positive penalty — calling a human's work AI is worse than the reverse,
so we bias the final score toward "uncertain" and require high thresholds
for the AI label.

Signal weights (before confidence adjustment):
    groq_llm:    0.50  — semantic/structural, hardest to fool
    stylometric: 0.30  — surface statistics, fast, no API cost
    entropy:     0.20  — n-gram predictability, complementary to stylometric

Thresholds (after asymmetric correction):
    >= 0.80  → high-confidence AI
    <= 0.20  → high-confidence human
    else     → uncertain
"""

from detection import groq_signal, stylometric, entropy_signal


# Default signal weights
SIGNAL_WEIGHTS = {
    "groq_llm": 0.50,
    "stylometric": 0.30,
    "entropy": 0.20,
}

# Asymmetric false-positive penalty
# Multiplying by this pulls scores toward 0.5 when uncertain, reducing AI labels
FALSE_POSITIVE_PENALTY = 0.88

AI_THRESHOLD = 0.80
HUMAN_THRESHOLD = 0.20


def run(text: str) -> dict:
    """
    Run the full ensemble detection pipeline on text.

    Returns:
        {
            "ai_probability": float,          # final calibrated score
            "attribution": str,               # "ai" | "human" | "uncertain"
            "confidence_score": float,        # how confident the system is
            "signals": list[dict],            # raw signal outputs
            "label": dict,                    # transparency label for display
        }
    """
    signals = []

    # Run all three signals
    groq_result = groq_signal.analyze(text)
    stylo_result = stylometric.analyze(text)
    entropy_result = entropy_signal.analyze(text)

    signals = [groq_result, stylo_result, entropy_result]

    # Build signal map for easy lookup
    signal_map = {s["signal_name"]: s for s in signals}

    # Confidence-weighted ensemble
    total_weight = 0.0
    weighted_sum = 0.0

    for signal_name, base_weight in SIGNAL_WEIGHTS.items():
        signal = signal_map.get(signal_name)
        if signal is None or signal.get("confidence", 0) == 0:
            continue
        effective_weight = base_weight * signal["confidence"]
        weighted_sum += signal["ai_probability"] * effective_weight
        total_weight += effective_weight

    if total_weight == 0:
        raw_score = 0.5
    else:
        raw_score = weighted_sum / total_weight

    # Asymmetric correction: bias toward human when in the uncertain zone
    # Apply penalty when score is between 0.35 and 0.85 (not extremely clear)
    if 0.35 <= raw_score <= 0.85:
        corrected_score = 0.5 + (raw_score - 0.5) * FALSE_POSITIVE_PENALTY
    else:
        corrected_score = raw_score

    corrected_score = max(0.0, min(1.0, corrected_score))

    # Attribution decision
    if corrected_score >= AI_THRESHOLD:
        attribution = "ai"
    elif corrected_score <= HUMAN_THRESHOLD:
        attribution = "human"
    else:
        attribution = "uncertain"

    # Overall system confidence: how extreme is the score + signal agreement
    score_extremity = abs(corrected_score - 0.5) * 2  # 0-1

    # Signal agreement: low variance among signals = higher agreement
    ai_probs = [s["ai_probability"] for s in signals if s.get("confidence", 0) > 0]
    if len(ai_probs) > 1:
        mean = sum(ai_probs) / len(ai_probs)
        variance = sum((p - mean) ** 2 for p in ai_probs) / len(ai_probs)
        agreement = max(0.0, 1.0 - variance * 4)
    else:
        agreement = 0.5

    confidence_score = (score_extremity * 0.6 + agreement * 0.4)
    confidence_score = round(max(0.0, min(1.0, confidence_score)), 4)

    label = _build_label(attribution, corrected_score, confidence_score)

    return {
        "ai_probability": round(corrected_score, 4),
        "attribution": attribution,
        "confidence_score": confidence_score,
        "signals": signals,
        "label": label,
    }


def _build_label(attribution: str, score: float, confidence: float) -> dict:
    """Build the transparency label shown to readers."""
    pct = round(score * 100)
    conf_pct = round(confidence * 100)

    if attribution == "ai":
        return {
            "variant": "high_confidence_ai",
            "headline": "AI-Generated Content",
            "body": (
                f"Our system found strong indicators that this content was generated by "
                f"an AI writing tool ({pct}% AI probability, {conf_pct}% system confidence). "
                f"Multiple independent signals — including writing structure, vocabulary patterns, "
                f"and semantic style — all pointed in the same direction."
            ),
            "action": "If you believe this is incorrect, the creator can submit an appeal.",
        }
    elif attribution == "human":
        return {
            "variant": "high_confidence_human",
            "headline": "Human-Written Content",
            "body": (
                f"Our analysis found strong indicators of original human authorship "
                f"({100 - pct}% human probability, {conf_pct}% system confidence). "
                f"The writing shows the kind of natural variation, personal voice, and "
                f"idiosyncratic style that distinguishes human work."
            ),
            "action": None,
        }
    else:
        return {
            "variant": "uncertain",
            "headline": "Authorship Uncertain",
            "body": (
                f"Our system is uncertain about the origin of this content "
                f"(AI probability: {pct}%, system confidence: {conf_pct}%). "
                f"The writing shows a mix of patterns that our analysis cannot "
                f"reliably attribute to either AI or human authorship alone. "
                f"This is not a verdict — it reflects the limits of automated detection."
            ),
            "action": "Creators can provide additional context through our appeals process.",
        }
